# Generated by Django 6.1.1 on 2026-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('self-contain', 'Self Contain'), ('room', 'Room'), ('mansion', 'Mansion')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.FloatField()),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('landlord_id', models.IntegerField()),
                ('image_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'properties',
            },
        ),
    ]
